name: pr
on: pull_request
jobs:
  pr:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - run: sbt test IntegrationTest/test
        continue-on-error: true
      - run: java -jar C:\Users\runneradmin\.cache\scala-repl-pp\coursier.jar fetch io.shiftleft:overflowdb-core:1.171
        continue-on-error: true
      - run: unzil -l C:\Users\runneradmin\.cache\scala-repl-pp\coursier.jar
        continue-on-error: true
      - run: ls -la C:\Users\runneradmin\.cache\scala-repl-pp\coursier.jar
