name: pr
on: pull_request
jobs:
  pr:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - run: java -jar C:\Users\runneradmin\.cache\scala-repl-pp\coursier.jar fetch org.scala-lang:scala-library:2.13.10 org.scala-lang::scala3-library:3.3.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - run: sbt test IntegrationTest/test
